parameters:
#    obdo_services.example.class: obdo\ServicesBundle\Example

services:
    obdo_services.AES:
        class: obdo\ServicesBundle\Services\AES

    obdo_services.Logger:
        class: obdo\ServicesBundle\Services\Logger
        arguments: [ @doctrine.orm.entity_manager ]
        
    obdo_services.Password:
        class: obdo\ServicesBundle\Services\Password
        arguments: [ @kernel ]
        
    obdo_services.Notifier:
        class: obdo\ServicesBundle\Services\Notifier
        arguments: [ @kernel ]
    
    obdo_services.Picture_uploader:
        class: obdo\ServicesBundle\Services\PictureUploader