obdo_kuchi_komi_rest:
    resource: "@obdoKuchiKomiRESTBundle/Controller/"
    type:     annotation
    prefix:   /

obdo_kuchi_komi:
    resource: "@obdoKuchiKomiBundle/Resources/config/routing.yml"
    prefix:   /
 
obdo_chart:
    resource: "@obdopChartBundle/Resources/config/routing.yml"
    prefix:   /
    
rest_Thanks:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\ThanksController
    
rest_Komi:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\KomiController
    
rest_Kuchi:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\KuchiController
    
rest_authenticate:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\AuthenticateController

rest_subscription:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\SubscriptionController
    
rest_subscription_group:
    type:       rest
    resource:   obdo\KuchiKomiRESTBundle\Controller\SubscriptionGroupController
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

