security:
    encoders:
        obdo\KuchiKomiUserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:             [ROLE_ADMIN_GROUP_KUCHI, ROLE_KUCHI]
        ROLE_ADMIN_GROUP_KUCHI: ROLE_KUCHI
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|console)|css|images|js)/
            security: false
            
        rest_api:
            pattern:        ^/rest
            anonymous:      true
        
        main_login:
            pattern:        ^/login$
            anonymous:      true
        main:
            pattern:        ^/
            anonymous:      false
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /login
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
    
    acl:
        connection: default
        
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user, roles: ROLE_ADMIN, requires_channel: http }
        - { path: ^/client, roles: ROLE_SUPER_ADMIN, requires_channel: http }
        