obdo_kuchi_komi_homepage:
    pattern:  /
    defaults: { _controller: obdoKuchiKomiBundle:Dashboard:index }

obdo_kuchi_komi_logs:
    pattern:  /logs/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Log:Log }
    requirements:
        sort: date_up|date_down|level_up|level_down|message_up|message_down
        
obdo_kuchi_komi_kuchi_group:
    pattern:  /kuchigroup/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down

obdo_kuchi_komi_kuchi_group_view:
    pattern:  /kuchigroup/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:view }
    
obdo_kuchi_komi_kuchi_group_add:
    pattern:  /kuchigroup
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:add }
    
obdo_kuchi_komi_kuchi:
    pattern:  /kuchi/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down|group_up|group_down

obdo_kuchi_komi_kuchi_add:
    pattern:  /kuchi/new/{groupId}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:add }
    
obdo_kuchi_komi_kuchi_view:
    pattern:  /kuchi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:view }