#obdo/KuchiKomiBundle/Resources/config/routing.yml

obdo_kuchi_komi_homepage:
    pattern:  /
    defaults: { _controller: obdoKuchiKomiBundle:Dashboard:index }

obdo_kuchi_komi_user:
    pattern:  /user/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:index }
    requirements:
        sort: name_up|name_down|role_up|role_down

obdo_kuchi_komi_user_add:
    pattern:  /user/add/
    defaults: { _controller: obdoKuchiKomiUserBundle:User:ajout }

obdo_kuchi_komi_user_add_suite:
    pattern:  /user/add/suite/{username}/{usermail}/{userpwd}/{userrole}/
    defaults: { _controller: obdoKuchiKomiUserBundle:User:ajoutsuite }

obdo_kuchi_komi_user_add_acl_kuchigroup:
    pattern:  /user/add/acl/kuchigroup/{userid}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:addaclkuchigroup }

obdo_kuchi_komi_user_add_acl_kuchi:
    pattern:  /user/add/acl/kuchi/{userid}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:addaclkuchi }

obdo_kuchi_komi_user_view:
    pattern:  /user/view/{id}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:view }
        
obdo_kuchi_komi_logs:
    pattern:  /logs/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Log:Log }
    requirements:
        sort: date_up|date_down|level_up|level_down|message_up|message_down
        
#Routes pour les kuchigroups
obdo_kuchi_komi_kuchi_group:
    pattern:  /kuchigroup/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down

obdo_kuchi_komi_kuchi_group_view:
    pattern:  /kuchigroup/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:view }
    
obdo_kuchi_komi_kuchi_group_add:
    pattern:  /kuchigroup
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:add }

obdo_kuchi_komi_kuchi_group_update:
    pattern:  /kuchigroup/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:update }
 
obdo_kuchi_komi_kuchi_group_activ:
    pattern:  /kuchigroup/activ/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:activ }
    
obdo_kuchi_komi_kuchi_group_delete:
    pattern:  /kuchigroup/delete/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:delete }

#Routes pour les kuchis
obdo_kuchi_komi_kuchi:
    pattern:  /kuchi/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down|group_up|group_down

obdo_kuchi_komi_komi:
    pattern:  /komi/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Komi:index }
    requirements:
        sort: active_up|active_down|creation_up|creation_down|suppression_up|suppression_down

obdo_kuchi_komi_komi_notification:
    pattern:  /komi/{id}/{page}/{sort}/notification
    defaults: { _controller: obdoKuchiKomiBundle:Komi:notification }
    
obdo_kuchi_komi_kuchi_add:
    pattern:  /kuchi/new/{groupId}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:add }
    
obdo_kuchi_komi_kuchi_view:
    pattern:  /kuchi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:view }

obdo_kuchi_komi_kuchi_update:
    pattern:  /kuchi/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:update }

# Route pour les kuchikomis
obdo_kuchi_komi_kuchikomi_view:
    pattern:  /kuchikomi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:view }

obdo_kuchi_komi_kuchikomi_add:
    pattern:  /kuchikomi/add/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:add }

#pour graphiques
obdo_pChart:
    pattern:  /graphique/{nom}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:choix }
    
obdo_pChart_kuchi:
    pattern:  /stat/kuchi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:kuchistat }

obdo_pChart_komi:
    pattern:  /stat/komi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:komistat }

obdo_pChart_subscription:
    pattern:  /stat/subscription
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:subscriptionstat }
    
obdo_pChart_kuchikomi:
    pattern:  /stat/kuchikomi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:kuchikomistat }

obdo_pChart_thanks:
    pattern:  /stat/thanks
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:thanksstat }
    
    
#Route pour test pChart, à virer ASAP
#pChart:
#    pattern: /pChart/
#    defaults: {_controller: obdopChartBundle:Examples:index }
#    
#pChart_index: 
#    pattern:  /index
#    defaults: { _controller: obdopChartBundle:Examples:index }
#
#pChart_view: 
#    pattern:  /view/{number}
#    defaults: { _controller: obdopChartBundle:Examples:view }
#
#pChart_example: 
#    pattern:  /example/{number}
#    defaults: { _controller: obdopChartBundle:Examples:example }