#obdo/KuchiKomiBundle/Resources/config/routing.yml

obdo_kuchi_komi_homepage:
    pattern:  /
    defaults: { _controller: obdoKuchiKomiBundle:Dashboard:index }

obdo_kuchi_komi_user:
    pattern:  /user/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:index }
    requirements:
        sort: name_up|name_down|role_up|role_down|login_up|login_down

obdo_kuchi_komi_user_add:
    pattern:  /user/add/{clientid}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:ajout, clientid: new }

obdo_kuchi_komi_user_add_suite:
    pattern:  /user/add/suite/{username}/{usermail}/{userclient}/{userpwd}/{userrole}/
    defaults: { _controller: obdoKuchiKomiUserBundle:User:ajoutsuite }

obdo_kuchi_komi_user_add_acl_kuchigroup:
    pattern:  /user/add/acl/kuchigroup/{userid}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:addaclkuchigroup }

obdo_kuchi_komi_user_add_acl_kuchi:
    pattern:  /user/add/acl/kuchi/{userid}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:addaclkuchi }

obdo_kuchi_komi_user_view:
    pattern:  /user/view/{id}
    defaults: { _controller: obdoKuchiKomiUserBundle:User:view }

obdo_kuchi_komi_user_remove:
    pattern: /client/user/remove/{clientid}/{userid}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:userremove }
        
obdo_kuchi_komi_logs:
    pattern:  /logs/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Log:Log }
    requirements:
        sort: date_up|date_down|level_up|level_down|message_up|message_down

#Routes pour les clients
obdo_kuchi_komi_client:
    pattern:  /client/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down

obdo_kuchi_komi_client_add:
    pattern:  /client/add/
    defaults: { _controller: obdoKuchiKomiBundle:Clients:add }

obdo_kuchi_komi_client_view:
    pattern:  /client/view/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:view }
    
obdo_kuchi_komi_client_update:
    pattern:  /client/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:update }

obdo_kuchi_komi_client_user:
    pattern:  /client/update/user/{clientid}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:user }
    
obdo_kuchi_komi_client_suivi:
    pattern:  /client/suivi/{clientid}
    defaults: { _controller: obdoKuchiKomiBundle:Clients:suivi }
    
obdo_kuchi_komi_abo_add:
    pattern: /client/abo/{clientid}
    defaults: { _controller: obdoKuchiKomiBundle:Abonnements:add }

obdo_kuchi_komi_abo_view:
    pattern: /client/abo/view/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Abonnements:view }

obdo_kuchi_komi_abo_update:
    pattern: /client/abo/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Abonnements:update }

obdo_kuchi_komi_abo_kuchi:
    pattern: /client/abo/kuchi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Abonnements:kuchi }

obdo_kuchi_komi_appel:
    pattern: /client/appel/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Appels:index }
    requirements:
        sort: name_up|name_down|date_up|date_down
        
obdo_kuchi_komi_appel_view:
    pattern:  /client/appel/view/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Appels:view }

obdo_kuchi_komi_appel_add:
    pattern:  /client/appel/add/
    defaults: { _controller: obdoKuchiKomiBundle:Appels:add }

obdo_kuchi_komi_kuchi_remove:
    pattern: /client/abo/kuchi/{id}/{aboid}
    defaults: { _controller: obdoKuchiKomiBundle:Abonnements:kuchiremove }

obdo_kuchi_komi_appel_suivi:
    pattern:  /client/appel/suivi/
    defaults: { _controller: obdoKuchiKomiBundle:Appels:suivi }
        
#Routes pour les kuchigroups
obdo_kuchi_komi_kuchi_group:
    pattern:  /kuchigroup/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down

obdo_kuchi_komi_kuchi_group_view:
    pattern:  /kuchigroup/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:view }
    
obdo_kuchi_komi_kuchi_group_add:
    pattern:  /kuchigroup
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:add }

obdo_kuchi_komi_kuchi_group_update:
    pattern:  /kuchigroup/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:update }
 
obdo_kuchi_komi_kuchi_group_activ:
    pattern:  /kuchigroup/activ/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:activ }
    
obdo_kuchi_komi_kuchi_group_delete:
    pattern:  /kuchigroup/delete/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiGroup:delete }

#Routes pour les komis
obdo_kuchi_komi_komi_view:
    pattern:  /komi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Komi:view }

obdo_kuchi_komi_komi:
    pattern:  /komi/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Komi:index }
    requirements:
        sort: active_up|active_down|creation_up|creation_down|suppression_up|suppression_down|synchronisation_up|synchronisation_down|os_up|os_down

obdo_kuchi_komi_komi_notification:
    pattern:  /komi/{id}/{page}/{sort}/notification
    defaults: { _controller: obdoKuchiKomiBundle:Komi:notification }
    

#Routes pour les kuchis
obdo_kuchi_komi_kuchi:
    pattern:  /kuchi/{page}/{sort}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:index }
    requirements:
        sort: active_up|active_down|name_up|name_down|creation_up|creation_down|suppression_up|suppression_down|group_up|group_down

obdo_kuchi_komi_kuchi_add:
    pattern:  /kuchi/new/{groupId}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:add }
    
obdo_kuchi_komi_kuchi_view:
    pattern:  /kuchi/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:view }

obdo_kuchi_komi_kuchi_update:
    pattern:  /kuchi/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:Kuchi:update }

# Route pour les kuchikomis
obdo_kuchi_komi_kuchikomi_index:
    pattern:  /kuchikomi/index
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:index }
    
obdo_kuchi_komi_kuchikomi_view:
    pattern:  /kuchikomi/view/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:view }

obdo_kuchi_komi_kuchikomi_add:
    pattern:  /kuchikomi/add/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:add }
    
obdo_kuchi_komi_kuchikomi_delete:
    pattern:  /kuchikomi/delete/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:delete }
    
obdo_kuchi_komi_kuchikomi_update:
    pattern:  /kuchikomi/update/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:update }
    
obdo_kuchi_komi_kuchikomi_addrecurrent:
    pattern: /kuchikomi/addrecurrent
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:addrecurrent }
    
obdo_kuchi_komi_kuchikomi_viewrecurrent:
    pattern: /kuchikomi/viewrecurrent/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:viewrecurrent }
    
obdo_kuchi_komi_kuchikomi_updaterecurrent:
    pattern:  /kuchikomi/updaterecurrent/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:updaterecurrent }
    
obdo_kuchi_komi_kuchikomi_deleterecurrent:
    pattern: /kuchikommi/deleterecurrent/{id}
    defaults: { _controller: obdoKuchiKomiBundle:KuchiKomi:deleterecurrent }
    
#pour graphiques
obdo_pChart:
    pattern:  /graphique/{nom}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:choix }
    
obdo_pChart_kuchi:
    pattern:  /stat/kuchi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:kuchistat }

obdo_pChart_komi:
    pattern:  /stat/komi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:komistat }

obdo_pChart_subscription:
    pattern:  /stat/subscription
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:subscriptionstat }
    
obdo_pChart_kuchikomi:
    pattern:  /stat/kuchikomi
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:kuchikomistat }

obdo_pChart_thanks:
    pattern:  /stat/thanks
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:thanksstat }
    
obdo_pChart_image:
    pattern:  /stat/image
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:imagestat }
    
obdo_pChart_creationjour:
    pattern:  /stat/creation/{mode}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:creationstat }
    
obdo_pChart_detail:
    pattern:  /stat/detail
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:detailstat } 

obdo_pChart_clientkuchikomi:
    pattern:  /stat/clientkuchikomi/{clientid}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:clientkuchikomistat }
   
obdo_pChart_appeldate:
    pattern:  /stat/appel/date/{mode}/{clientid}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:appeldatestat } 

obdo_pChart_appeltype:
    pattern:  /stat/appel/type/{mode}/{clientid}
    defaults: { _controller: obdopChartBundle:KuchiKomiStat:appeltypestat } 
    
#Route pour test pChart, à virer ASAP
#pChart:
#    pattern: /pChart/
#    defaults: {_controller: obdopChartBundle:Examples:index }
#    
#pChart_index: 
#    pattern:  /index
#    defaults: { _controller: obdopChartBundle:Examples:index }
#
#pChart_view: 
#    pattern:  /view/{number}
#    defaults: { _controller: obdopChartBundle:Examples:view }
#
#pChart_example: 
#    pattern:  /example/{number}
#    defaults: { _controller: obdopChartBundle:Examples:example }