parameters:
#    obdo_kuchi_komi_menu.example.class: obdo\KuchiKomiMenuBundle\Example

services:
#    obdo_kuchi_komi_menu.example:
#        class: %obdo_kuchi_komi_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
