<?php

namespace obdo\KuchiKomiRESTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KuchiAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuchiAccountRepository extends EntityRepository
{
    
    public function getKuchiAccountForKuchi( $kuchi )
    {
    	$qb = $this->createQueryBuilder('kuchiAccount')
                ->join('kuchiAccount.kuchi', 'kuchi', 'WITH', 'kuchi = :kuchi')
                ->setParameter('kuchi', $kuchi )
                ->join('kuchiAccount.komi', 'komi', 'WITH', 'komi.active = true');
    
    	return $qb->getQuery()->getResult();
    }
}
