<?php

namespace obdo\KuchiKomiRESTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KuchiKomiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuchiKomiRepository extends EntityRepository
{
    public function getNbKuchiKomi()
    {
        return $this->createQueryBuilder('kuchikomi')
                    ->select('COUNT(kuchikomi)')
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
