<?php

namespace obdo\KuchiKomiRESTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    public function getNbSubscription()
    {
        return $this->createQueryBuilder('subscription')
                    ->select('COUNT(subscription)')
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
