parameters:
#    obdo_kuchi_komi_user.example.class: obdo\KuchiKomiUserBundle\Example

services:
#    obdo_kuchi_komi_user.example:
#        class: %obdo_kuchi_komi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
