pChart_index: 
    pattern:  /index
    defaults: { _controller: obdopChartBundle:Examples:index }

pChart_view: 
    pattern:  /view/{number}
    defaults: { _controller: obdopChartBundle:Examples:view }

pChart_example: 
    pattern:  /example/{number}
    defaults: { _controller: obdopChartBundle:Examples:example }
