## src/obdo/KuchiKomiRESTBundle/Resources/config/validation.yml
obdo\KuchiKomiRESTBundle\Entity\KuchiGroup:
    properties:
        logoimg:
            - File:
                mimeTypes: [image/png, image/gif, image/jpg, image/jpeg]

obdo\KuchiKomiRESTBundle\Entity\Kuchi:
    properties:
        logoimg:
            - File:
                mimeTypes: [image/png, image/gif, image/jpg, image/jpeg]
        photoimg:
            - File:
                mimeTypes: [image/png, image/gif, image/jpg, image/jpeg]
                
